name: Build and Deploy Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Installing the nodeJs
      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # Step 3: Installing the Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Test the Angular app
      - name: Run tests
        run: npm run test:headless

      # Step 5: Run linting for the Angular app
      # - name: Run Lint
      #   run: npm run lint

      # Step 6: Build the Angular app
      - name: Build Angular App
        run: npm run build

      # Stpe 7: Copy and rename the index.html to 4o4.html
      - name: Rename index.html to 404.html
        run: cp dist/angular-2023/index.html dist/angular-2023/404.html

      # Step 8: Install dependencies
      - name: Deploy to gh pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }} # Ensure GH_TOKEN is set in Secrets
          publish_dir: dist/angular-2023 # Adjust this path as needed
          enable_jekyll: true # Set to false if you don't want Jekyll processing
